# -*- coding: utf-8 -*-
"""DataScience_Salaries_EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CFGlZqM-bLcX3Atz6lEknepzO73cx71

### 1. Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import streamlit as st

"""### 2. Load Dataset"""

df = pd.read_csv("DataScience_salaries_cleaned.csv")

df.head()
df.shape
df.info()
df.describe()

"""## Phase 2: Data Cleaning"""

# Check missing values
df.isnull().sum()

# Remove Duplicate Records
df.duplicated().sum()

# df.drop_duplicates(inplace=True)

# Standardize Column Names
df.columns = df.columns.str.lower().str.strip()

# Validate Data Types
df.dtypes

df['work_year'] = df['work_year'].astype(int)
df['salary_in_usd'] = df['salary_in_usd'].astype(float)

categorical_cols = ['experience_level','employment_type','job_title',
                    'salary_currency','employee_residence',
                    'company_location','company_size']

df[categorical_cols] = df[categorical_cols].astype('category')

# Verify Currency Standardization
df['salary_currency'].value_counts()

# Validate Experience Level Encoding
df['experience_level'] = df['experience_level'].map({
            'EN':'Entry',
            'MI':'Mid',
            'SE':'Senior',
            'EX':'Executive'
            })

# Validate Remote Work Ratio
df['remote_ratio'].unique()

# Detect Salary Outliers
df['salary_in_usd'].describe()

# 10. Reset Index After Cleaning
df.reset_index(drop=True, inplace=True)

#  11. Save the Cleaned Dataset
df.to_csv("cleaned_datascience_salaries.csv", index=False)

"""## Phase 3: Feature Engineering"""

# 3.1. Create Experience Level Numeric Encoding
experience_map = {
    'Entry': 1,
    'Mid': 2,
    'Senior': 3,
    'Executive': 4
}

df['experience_level_num'] = df['experience_level'].map(experience_map).astype(int)

# 3.2. Create Remote Work Category
df['remote_category'] = df['remote_ratio'].replace({
    0: 'Onsite',
    50: 'Hybrid',
    100: 'Remote'
})

# 3.3. Create Company Size Numeric Encoding
company_size_map = {
    'S': 1,
    'M': 2,
    'L': 3
}

df['company_size_num'] = df['company_size'].map(company_size_map)

# 3.4. Create Employment Type Category
df['employment_type_full'] = df['employment_type'].map({
    'FT': 'Full Time',
    'PT': 'Part Time',
    'CT': 'Contract',
    'FL': 'Freelance'
})

# 3.5. Create Salary Log Transformation
df['log_salary'] = np.log(df['salary_in_usd'])

# 3.6. Create Salary Bands
df['salary_band'] = pd.cut(
    df['salary_in_usd'],
    bins=[0, 50000, 100000, 150000, 200000, 300000],
    labels=['Low', 'Medium', 'High', 'Very High', 'Executive']
)

# 3.7. Create Region Feature
def region_mapper(country):
    if country in ['US', 'CA']:
        return 'North America'
    elif country in ['GB', 'DE', 'FR', 'ES']:
        return 'Europe'
    elif country in ['IN', 'SG', 'JP', 'CN']:
        return 'Asia'
    else:
        return 'Other'

df['region'] = df['company_location'].apply(region_mapper)

# 3.8. Extract Year-Based Features
df['years_since_2020'] = df['work_year'] - 2020

# 3.9. Create Job Title Category
def categorize_job(title):

    title = title.lower()

    if 'scientist' in title:
        return 'Data Scientist'
    elif 'analyst' in title:
        return 'Data Analyst'
    elif 'engineer' in title:
        return 'ML Engineer'
    elif 'manager' in title or 'lead' in title:
        return 'Manager'
    else:
        return 'Other'

df['job_category'] = df['job_title'].apply(categorize_job)

df.to_csv("feature_engineered_datascience_salaries.csv", index=False)

"""## Phase 4: Univariate Analysis"""

df['salary_in_usd'].describe()

plt.figure(figsize=(8,5))
sns.histplot(df['salary_in_usd'], kde=True)
plt.title("Distribution of Data Science Salaries (USD)")
plt.xlabel("Salary in USD")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df['salary_in_usd'])
plt.title("Salary Distribution with Outliers")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='experience_level', data=df)
plt.title("Distribution of Experience Levels")
plt.xlabel("Experience Level")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='employment_type', data=df)
plt.title("Distribution of Employment Types")
plt.xlabel("Employment Type")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='remote_ratio', data=df)
plt.title("Remote Work Distribution")
plt.xlabel("Remote Work Ratio")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='company_size', data=df)
plt.title("Company Size Distribution")
plt.xlabel("Company Size")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='salary_band', data=df)
plt.title("Salary Band Distribution")
plt.xlabel("Salary Category")
plt.ylabel("Number of Employees")
plt.show()

"""Top Job Titles"""

df['job_title'].value_counts().head(10)

plt.figure(figsize=(10,6))
df['job_title'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Data Science Job Titles")
plt.xlabel("Job Title")
plt.ylabel("Count")
plt.show()

"""## Phase 5: Bivariate Analysis"""

plt.figure(figsize=(8,5))
sns.boxplot(x='experience_level', y='salary_in_usd', data=df)
plt.title("Salary Distribution by Experience Level")
plt.xlabel("Experience Level")
plt.ylabel("Salary in USD")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='employment_type', y='salary_in_usd', data=df)
plt.title("Salary Distribution by Employment Type")
plt.xlabel("Employment Type")
plt.ylabel("Salary in USD")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='company_size', y='salary_in_usd', data=df)
plt.title("Salary Distribution by Company Size")
plt.xlabel("Company Size")
plt.ylabel("Salary in USD")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='remote_ratio', y='salary_in_usd', data=df)
plt.title("Salary vs Remote Work Ratio")
plt.xlabel("Remote Work Ratio")
plt.ylabel("Salary in USD")
plt.show()

plt.figure(figsize=(8,5))
sns.lineplot(x='work_year', y='salary_in_usd', data=df)
plt.title("Salary Trend Over Years")
plt.xlabel("Year")
plt.ylabel("Average Salary in USD")
plt.show()

top_jobs = df['job_title'].value_counts().head(10).index

plt.figure(figsize=(12,6))
sns.boxplot(x='job_title', y='salary_in_usd', data=df[df['job_title'].isin(top_jobs)])
plt.xticks(rotation=90)
plt.title("Salary Distribution for Top Data Science Roles")
plt.xlabel("Job Title")
plt.ylabel("Salary in USD")
plt.show()

top_roles = df['job_title'].value_counts().head(10).index

top_roles_df = df[df['job_title'].isin(top_roles)]

avg_salary_top_roles = (
    top_roles_df.groupby('job_title')['salary_in_usd']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

print(avg_salary_top_roles)

avg_salary_top_roles.to_csv(
    "average_salary_top_roles.csv",
    index=False
)

top_locations = df['company_location'].value_counts().head(10).index

plt.figure(figsize=(10,6))
sns.boxplot(x='company_location', y='salary_in_usd',
            data=df[df['company_location'].isin(top_locations)])
plt.xticks(rotation=90)
plt.title("Salary by Company Location")
plt.xlabel("Company Location")
plt.ylabel("Salary in USD")
plt.show()

"""## Phase 6: Correlation Analysis & Category-Based Analysis"""

numeric_df = df.select_dtypes(include=['int64','float64'])

correlation_matrix = numeric_df.corr()

print(correlation_matrix)

numeric_cols = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix of Numerical Variables")
plt.show()

sns.pairplot(df[['salary_in_usd','experience_level_num','company_size_num','remote_ratio']])
plt.show()

numeric_df = df.select_dtypes(include=['int64','float64'])

correlation_matrix = numeric_df.corr()

plt.figure(figsize=(8,6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")

plt.title("Correlation Matrix of Numerical Variables")
plt.show()

df.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x='experience_level', y='salary_in_usd', data=df)
plt.title("Average Salary by Experience Level")
plt.show()

df.groupby('company_size')['salary_in_usd'].mean()

plt.figure(figsize=(8,5))
sns.barplot(x='company_size', y='salary_in_usd', data=df)
plt.title("Average Salary by Company Size")
plt.show()

df.groupby('remote_category')['salary_in_usd'].mean()

plt.figure(figsize=(8,5))
sns.barplot(x='remote_category', y='salary_in_usd', data=df)
plt.title("Average Salary by Remote Work Type")
plt.show()

df.groupby('job_category')['salary_in_usd'].mean().sort_values(ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(x='job_category', y='salary_in_usd', data=df)
plt.xticks(rotation=90)
plt.title("Average Salary by Job Category")
plt.show()

top_locations = df['company_location'].value_counts().head(10).index

location_salary = df[df['company_location'].isin(top_locations)]

plt.figure(figsize=(10,6))
sns.barplot(x='company_location', y='salary_in_usd', data=location_salary)
plt.xticks(rotation=90)
plt.title("Average Salary by Company Location")
plt.show()

"""##### Average Salary by Company Location"""

salary_by_location = (
    df.groupby('company_location')['salary_in_usd']
    .mean()
    .reset_index()
)

salary_by_location = salary_by_location.rename(
    columns={'salary_in_usd': 'average_salary_usd'}
)

salary_by_location = salary_by_location.sort_values(
    by='average_salary_usd',
    ascending=False
)

print(salary_by_location)


salary_by_location['average_salary_usd'] = salary_by_location[
    'average_salary_usd'
].round(2)

print(salary_by_location)

salary_by_location.to_csv(
    "average_salary_by_location.csv",
    index=False
)

salary_trend = df.groupby('work_year')['salary_in_usd'].mean()

plt.figure(figsize=(8,5))
salary_trend.plot(marker='o')
plt.title("Average Salary Trend (2020–2025)")
plt.xlabel("Year")
plt.ylabel("Average Salary in USD")
plt.show()

"""## Phase 7: Financial Modeling: Predict Salary Using Linear Regression"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y = df['salary_in_usd']

X = df[['experience_level_num',
        'company_size_num',
        'remote_ratio',
        'years_since_2020']]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

"""##### Once the model is trained, generate salary predictions"""

y_pred = model.predict(X_test)

"""#### Evaluate the model using common regression metrics"""

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coefficients)

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Salary")
plt.ylabel("Predicted Salary")
plt.title("Actual vs Predicted Salary")
plt.show()

"""## Phase 8- Business Insights

'''
### 1. Experience Level is the Strongest Salary Driver

Analysis consistently shows that salary increases significantly with experience level.

Entry-level professionals earn the lowest salaries, while senior and executive professionals command the highest compensation. The salary gap between entry-level and senior roles can be substantial because organizations value domain expertise, leadership ability, and strategic decision-making skills.

Business implication:

Companies must design clear career progression frameworks because salary growth strongly depends on experience and role maturity.

For job seekers, upskilling and gaining practical experience has a direct impact on long-term earning potential.

### 2. Certain Job Roles Command Premium Salaries

Some job roles consistently show higher salary ranges than others.

High-paying roles typically include:

• Machine Learning Engineer
• AI Engineer
• Data Science Manager
• Applied Scientist

Lower average salaries are generally associated with:

• Data Analyst
• Junior Data Scientist
• Business Intelligence Analyst

Business implication:

Organizations investing in advanced AI and machine learning capabilities tend to offer higher compensation to attract specialized talent.

### 3. Larger Companies Offer Higher Salaries

The analysis shows that large organizations generally pay more than small companies.

This occurs because larger organizations:

• Have higher budgets
• Require complex data infrastructure
• Operate at global scale
• Need specialized expertise

Business implication:

Startups often compensate with equity or growth opportunities, while larger enterprises compete through higher base salaries.

### 4. Remote Work Has Limited Impact on Salary

The dataset indicates that remote work does not significantly reduce salaries in the data science industry.

Fully remote roles frequently offer salaries comparable to on-site positions.

Business implication:

The data science labor market has become location-flexible, enabling organizations to recruit talent globally without major salary reductions.

### 5. Geographic Location Strongly Influences Salary

Salary levels vary widely depending on company location.

Countries with the highest compensation levels typically include:

• United States
• Canada
• Western Europe

Lower average salaries are observed in developing markets.

Business implication:

Global companies may adopt geo-adjusted salary strategies, where compensation varies depending on employee location.

### 6. Data Science Salaries Have Increased Over Time

The analysis of yearly trends from 2020 to 2025 shows a steady rise in average salaries.

Key reasons include:

• Increasing demand for AI and machine learning expertise
• Digital transformation across industries
• Data-driven decision making becoming standard practice

Business implication:

Organizations that rely heavily on data analytics must expect continued salary inflation in the data talent market.

### 7. Salary Prediction Models Highlight Key Predictors

The regression model identified the following as important predictors of salary:

• Experience level
• Company size
• Job role
• Work year (market trend)

### Business implication:

HR departments can use predictive models to benchmark salary offers and maintain competitive compensation packages.

Summary of Key Salary Drivers

Salary in the data science industry is primarily influenced by the following factors:

Experience Level
↓
Job Role Specialization
↓
Company Size
↓
Geographic Location
↓
Industry Demand Trends

These variables explain most of the variation in salaries across the dataset.

Strategic Takeaways

For Companies:

• Invest in experienced data professionals
• Offer competitive compensation for specialized AI roles
• Use remote hiring to expand the talent pool

For Job Seekers:

• Focus on high-demand roles such as machine learning engineering
• Gain experience through real-world projects
• Develop advanced technical skills in AI and data science
'''

## Phase 9 — Final Dashboard, Reporting and Export Pipeline
"""

dashboard_df = df[[
    'work_year',
    'experience_level',
    'employment_type',
    'job_category',
    'salary_in_usd',
    'company_size',
    'remote_category',
    'region',
    'company_location'
]]

dashboard_df.to_csv("dashboard_datascience_salary.csv", index=False)

salary_by_experience = df.groupby('experience_level')['salary_in_usd'].mean().reset_index()

salary_by_role = df.groupby('job_category')['salary_in_usd'].mean().reset_index()

salary_by_company = df.groupby('company_size')['salary_in_usd'].mean().reset_index()

salary_trend = df.groupby('work_year')['salary_in_usd'].mean().reset_index()

salary_by_experience.to_csv("salary_by_experience.csv", index=False)
salary_by_role.to_csv("salary_by_role.csv", index=False)
salary_by_company.to_csv("salary_by_company.csv", index=False)
salary_trend.to_csv("salary_trend.csv", index=False)

plt.figure(figsize=(8,5))
sns.barplot(x='experience_level', y='salary_in_usd', data=df)
plt.title("Average Salary by Experience Level")
plt.show()

plt.figure(figsize=(8,5))
sns.lineplot(x='work_year', y='salary_in_usd', data=df)
plt.title("Salary Trend (2020–2025)")
plt.show()

plt.figure(figsize=(10,6))
sns.barplot(x='job_category', y='salary_in_usd', data=df)
plt.xticks(rotation=90)
plt.title("Salary by Job Category")
plt.show()

"""## Bonus: Interactive Dashboards with Streamlit"""

# Page configuration
st.set_page_config(page_title="Data Science Salary Dashboard",
                   layout="wide")

st.title("📊 Data Science Salary Analytics Dashboard (2020–2025)")

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv("dashboard_datascience_salary.csv")
    return df

df = load_data()

# Sidebar filters
st.sidebar.header("Filters")

experience = st.sidebar.multiselect(
    "Select Experience Level",
    options=df['experience_level'].unique(),
    default=df['experience_level'].unique()
)

company_size = st.sidebar.multiselect(
    "Select Company Size",
    options=df['company_size'].unique(),
    default=df['company_size'].unique()
)

df_filtered = df[
    (df['experience_level'].isin(experience)) &
    (df['company_size'].isin(company_size))
]

# KPI Metrics
st.subheader("Key Metrics")

col1, col2, col3 = st.columns(3)

col1.metric("Average Salary",
            f"${int(df_filtered['salary_in_usd'].mean()):,}")

col2.metric("Max Salary",
            f"${int(df_filtered['salary_in_usd'].max()):,}")

col3.metric("Total Jobs",
            len(df_filtered))

st.divider()

# Salary Trend
st.subheader("Salary Trend Over Time")

trend = df_filtered.groupby("work_year")["salary_in_usd"].mean()

fig, ax = plt.subplots()
trend.plot(marker="o", ax=ax)
ax.set_xlabel("Year")
ax.set_ylabel("Average Salary (USD)")
ax.set_title("Average Salary Trend")

st.pyplot(fig)

# Salary by Experience Level
st.subheader("Average Salary by Experience Level")

fig, ax = plt.subplots()

sns.barplot(
    data=df_filtered,
    x="experience_level",
    y="salary_in_usd",
    ax=ax
)

ax.set_title("Salary by Experience Level")
st.pyplot(fig)

# Salary by Company Size
st.subheader("Salary by Company Size")

fig, ax = plt.subplots()

sns.barplot(
    data=df_filtered,
    x="company_size",
    y="salary_in_usd",
    ax=ax
)

ax.set_title("Salary by Company Size")
st.pyplot(fig)

# Job Category Analysis
st.subheader("Salary by Job Category")

fig, ax = plt.subplots(figsize=(10,5))

sns.barplot(
    data=df_filtered,
    x="job_category",
    y="salary_in_usd",
    ax=ax
)

plt.xticks(rotation=45)

st.pyplot(fig)

# Location Analysis
st.subheader("Top Company Locations")

top_locations = (
    df_filtered.groupby("company_location")["salary_in_usd"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

fig, ax = plt.subplots()

top_locations.plot(kind="bar", ax=ax)

ax.set_title("Top 10 Locations by Average Salary")

st.pyplot(fig)

"""#### Run Dashbarod Locally"""

streamlit run streamlit_dashboard.py